global:
  mounts:
    - ~/.claude-sandbox/.gitconfig:/home/claude/.gitconfig:ro
    - ~/.claude-sandbox/skills:/home/claude/.claude/skills:ro
    - ~/.claude-sandbox/rules:/home/claude/.claude/rules:ro
projects:
  /home/lhvubtqn/workdir/mattle-fun/godew-valley:
    credentials:
      type: ssh
      keyPath: /home/lhvubtqn/.ssh/id_ed25519_godew-valley
    mounts:
      - /home/lhvubtqn/.local/bin/godot_v4.6.2:/home/claude/.local/godot
